# knife4j
knife4j:
  enable: true
  setting:
    language: zh-CN
  openapi:
    title: 技术派
    description: 一个基于SpringBoot、MyBatis-Plus、MySQL、Redis、ElasticSearch、MongoDB、Docker、RabbitMQ等技术栈实现的社区系统，采用主流的互联网技术架构、全新的UI设计、支持一键源码部署，拥有完整的文章&教程发布/搜索/评论/统计流程等。
    version: 1.0.0
    concat:
      - qzh
      - https://github.com/RelishCoding/paicoding-forum
    license: Apache License 2.0
    license-url: https://github.com/itwanger/paicoding/blob/main/License
    email: qzh2806894439@163.com
    group:
      admin:
        group-name: 后台接口分组
        api-rule: package
        api-rule-resources:
          - com.paicoding.web.admin

      front:
        group-name: 前台接口分组
        api-rule: package
        api-rule-resources:
          - com.paicoding.web.front

